// Auto-generated from https://opendata.mtr.com.hk/data/mtr_bus_stops.csv
// Regenerate: node scripts/gen-bus-stops.mjs
export const BUS_STOP_NAMES: Record<string, { en: string; tc: string }> = {
  "506-D010": {"en":"Siu Lun","tc":"兆麟"},
  "506-D020": {"en":"Yau Oi Estate","tc":"友愛邨"},
  "506-D030": {"en":"LR Town Centre Stop","tc":"輕鐵市中心站"},
  "506-D040": {"en":"LR Tuen Mun Stop","tc":"輕鐵屯門站"},
  "506-D050": {"en":"LR Kin On Stop","tc":"輕鐵建安站"},
  "506-D060": {"en":"LR Tsing Wun Stop","tc":"輕鐵青雲站"},
  "506-D070": {"en":"SKH St. Peter's Church","tc":"聖彼得堂"},
  "506-D080": {"en":"Glorious Garden","tc":"富健花園"},
  "506-D090": {"en":"Sun Tuen Mun Centre","tc":"新屯門中心"},
  "506-D100": {"en":"LR Butterfly Stop","tc":"輕鐵蝴蝶站"},
  "506-D110": {"en":"Tip Sum House, Butterfly Estate","tc":"蝴蝶邨蝶心樓"},
  "506-D120": {"en":"Wu Pik House, Wu King Estate","tc":"湖景邨湖碧樓"},
  "506-D130": {"en":"Pierhead Garden","tc":"海翠花園"},
  "506-D140": {"en":"Tuen Mun Ferry Pier","tc":"屯門碼頭"},
  "506-U010": {"en":"Tuen Mun Ferry Pier","tc":"屯門碼頭"},
  "506-U020": {"en":"Melody Garden","tc":"美樂花園"},
  "506-U030": {"en":"LR Butterfly Stop","tc":"輕鐵蝴蝶站"},
  "506-U040": {"en":"Light Rail Depot Stop","tc":"輕鐵車廠站"},
  "506-U045": {"en":"Glorious Garden","tc":"富健花園"},
  "506-U050": {"en":"LR Lung Mun Stop","tc":"輕鐵龍門站"},
  "506-U060": {"en":"LR Tsing Wun Stop","tc":"輕鐵青雲站"},
  "506-U070": {"en":"LR Kin On Stop","tc":"輕鐵建安站"},
  "506-U075": {"en":"Tuen Mun Station","tc":"屯門站"},
  "506-U080": {"en":"MTR Tuen Mun Station","tc":"港鐵屯門站"},
  "506-U090": {"en":"Tuen Mun Town Centre","tc":"屯門市中心"},
  "506-U100": {"en":"On Ting Estate","tc":"安定邨"},
  "506-U110": {"en":"LR Sam Shing Stop","tc":"輕鐵三聖站"},
  "506-U120": {"en":"Siu Lun","tc":"兆麟"},
  "K12-D010": {"en":"Eightland Garden","tc":"八號花園"},
  "K12-D020": {"en":"Tai Po Mega Mall","tc":"大埔超級城"},
  "K12-D030": {"en":"Uptown Plaza","tc":"新達廣場"},
  "K12-D040": {"en":"Tai Po Market Station","tc":"大埔墟站"},
  "K12-U010": {"en":"Tai Po Market Station","tc":"大埔墟站"},
  "K12-U020": {"en":"Tai Po Mega Mall","tc":"大埔超級城"},
  "K12-U030": {"en":"Eightland Garden","tc":"八號花園"},
  "K14-D010": {"en":"Tai Po Mega Mall","tc":"大埔超級城"},
  "K14-D020": {"en":"Uptown Plaza","tc":"新達廣場"},
  "K14-D030": {"en":"Tai Po Market Station","tc":"大埔墟站"},
  "K17-D010": {"en":"Fu Shin","tc":"富善"},
  "K17-D020": {"en":"Uptown Plaza","tc":"新達廣場"},
  "K17-D030": {"en":"Tai Po Market Station","tc":"大埔墟站"},
  "K17-U010": {"en":"Tai Po Market Station","tc":"大埔墟站"},
  "K17-U020": {"en":"Tai Po Centre Phase 5","tc":"大埔中心第五期"},
  "K17-U030": {"en":"Yee Nga Court","tc":"怡雅苑"},
  "K17-U040": {"en":"Fu Shin","tc":"富善"},
  "K18-D010": {"en":"Kwong Fuk","tc":"廣福"},
  "K18-D020": {"en":"Uptown Plaza","tc":"新達廣場"},
  "K18-D030": {"en":"Tai Po Market Station","tc":"大埔墟站"},
  "K18-U010": {"en":"Tai Po Market Station","tc":"大埔墟站"},
  "K18-U020": {"en":"Wang Fuk Court","tc":"宏福苑"},
  "K18-U030": {"en":"Kwong Fuk","tc":"廣福"},
  "K51-D010": {"en":"Tai Lam","tc":"大欖"},
  "K51-D020": {"en":"Siu Lam","tc":"小欖"},
  "K51-D030": {"en":"Ching Lai Road Siu Lam","tc":"小欖澄麗路"},
  "K51-D040": {"en":"Siu Lam Tsuen","tc":"小欖村"},
  "K51-D050": {"en":"Siu Lam San Tsuen","tc":"小欖新村"},
  "K51-D060": {"en":"The Aegean","tc":"愛琴灣"},
  "K51-D070": {"en":"Siu Sau Sheung Tsuen","tc":"小秀上村"},
  "K51-D080": {"en":"Pearl Island","tc":"龍珠島"},
  "K51-D090": {"en":"Hong Kong Gold Coast","tc":"香港黃金海岸"},
  "K51-D100": {"en":"Golden Beach","tc":"黃金泳灘"},
  "K51-D110": {"en":"Cafeteria Beach","tc":"咖啡灣"},
  "K51-D120": {"en":"Bayview Terrace","tc":"碧翠花園"},
  "K51-D130": {"en":"Castle Peak Bay Pier","tc":"青山灣碼頭"},
  "K51-D140": {"en":"Sam Shing Estate","tc":"三聖邨"},
  "K51-D150": {"en":"Hanford Garden (LR Sam Shing Stop)","tc":"恆福花園 (輕鐵三聖站)"},
  "K51-D160": {"en":"Mrs Aw Boon Haw Secondary School","tc":"胡陳金枝中學"},
  "K51-D170": {"en":"Tsing Sin Playground","tc":"青善遊樂場"},
  "K51-D180": {"en":"Chi Lok Fa Yuen","tc":"置樂花園"},
  "K51-D190": {"en":"Tuen Mun Government Secondary School","tc":"屯門官立中學"},
  "K51-D200": {"en":"LR Town Centre Stop","tc":"輕鐵市中心站"},
  "K51-D210": {"en":"MTR Tuen Mun Station (LR Tuen Mun Stop)","tc":"港鐵屯門站 (輕鐵屯門站)"},
  "K51-D220": {"en":"SKH St. Simon's Lui Ming Choi Secondary School","tc":"聖公會聖西門呂明才中學"},
  "K51-D230": {"en":"Prime View Garden","tc":"景峰花園"},
  "K51-D240": {"en":"LR Fung Tei Stop","tc":"輕鐵鳳地站"},
  "K51-D250": {"en":"MTR Siu Hong Station (South)","tc":"港鐵兆康站 (南)"},
  "K51-D260": {"en":"Brilliant Garden","tc":"彩暉花園"},
  "K51-D270": {"en":"Lingnan University","tc":"嶺南大學"},
  "K51-D280": {"en":"South Hillcrest","tc":"倚嶺南庭"},
  "K51-D290": {"en":"Fu Tai","tc":"富泰"},
  "K51-U010": {"en":"Fu Tai","tc":"富泰"},
  "K51-U020": {"en":"Beneville","tc":"聚康山莊"},
  "K51-U030": {"en":"Lingnan University","tc":"嶺南大學"},
  "K51-U040": {"en":"Brilliant Garden","tc":"彩暉花園"},
  "K51-U050": {"en":"MTR Siu Hong Station (South)","tc":"港鐵兆康站 (南)"},
  "K51-U060": {"en":"Tseng Choi Street","tc":"井財街"},
  "K51-U070": {"en":"ACME Shopping Arcade","tc":"雅都商場"},
  "K51-U080": {"en":"Tak Ching Court (MTR Tuen Mun Station)","tc":"德政圍 (港鐵屯門站)"},
  "K51-U090": {"en":"Tuen Mun Town Centre (LR Town Centre Stop)","tc":"屯門市中心 (輕鐵市中心站)"},
  "K51-U100": {"en":"Tuen Mun Government Secondary School","tc":"屯門官立中學"},
  "K51-U110": {"en":"Handsome Court","tc":"恒順園"},
  "K51-U120": {"en":"Harvest Garden","tc":"恒豐園"},
  "K51-U130": {"en":"Sam Shing Estate","tc":"三聖邨"},
  "K51-U140": {"en":"Castle Peak Beach","tc":"青山灣"},
  "K51-U150": {"en":"Seaview Garden","tc":"海景花園"},
  "K51-U160": {"en":"Cafeteria Beach","tc":"咖啡灣"},
  "K51-U170": {"en":"Golden Beach","tc":"黃金泳灘"},
  "K51-U180": {"en":"Hong Kong Gold Coast","tc":"香港黃金海岸"},
  "K51-U190": {"en":"Kar Wo Lei Tsuen","tc":"嘉禾里村"},
  "K51-U200": {"en":"Siu Sau Tsuen","tc":"小秀村"},
  "K51-U210": {"en":"The Aegean","tc":"愛琴灣"},
  "K51-U220": {"en":"Siu Lam San Tsuen","tc":"小欖新村"},
  "K51-U230": {"en":"Siu Lam Tsuen","tc":"小欖村"},
  "K51-U240": {"en":"Ching Lai Road Siu Lam","tc":"小欖澄麗路"},
  "K51-U250": {"en":"Tai Lam","tc":"大欖"},
  "K51A-D010": {"en":"So Kwun Wat Tsuen","tc":"掃管笏村"},
  "K51A-D020": {"en":"So Kwun Wat (Mrs. Cheng Yam On Millennium School)","tc":"掃管笏 (鄭任安夫人千禧小學)"},
  "K51A-D030": {"en":"So Kwun Wat Road","tc":"掃管笏路"},
  "K51A-D040": {"en":"18 Kwun Chui Road","tc":"管翠路18號"},
  "K51A-D050": {"en":"Kwun Chui Road","tc":"管翠路"},
  "K51A-D060": {"en":"Aegean Coast","tc":"愛琴海岸"},
  "K51A-D070": {"en":"Hong Kong Gold Coast","tc":"香港黃金海岸"},
  "K51A-D080": {"en":"Golden Beach","tc":"黃金泳灘"},
  "K51A-D090": {"en":"Cafeteria Beach","tc":"咖啡灣"},
  "K51A-D100": {"en":"Bayview Terrace","tc":"碧翠花園"},
  "K51A-D110": {"en":"Castle Peak Bay Pier","tc":"青山灣碼頭"},
  "K51A-D120": {"en":"Sam Shing Estate","tc":"三聖邨"},
  "K51A-D140": {"en":"Mrs Aw Boon Haw Secondary School","tc":"胡陳金枝中學"},
  "K51A-D150": {"en":"Tsing Sin Playground","tc":"青善遊樂場"},
  "K51A-D160": {"en":"Chi Lok Fa Yuen","tc":"置樂花園"},
  "K51A-D170": {"en":"Tuen Mun Government Secondary School","tc":"屯門官立中學"},
  "K51A-D180": {"en":"LR Town Centre Stop","tc":"輕鐵市中心站"},
  "K51A-D190": {"en":"MTR Tuen Mun Station (LR Tuen Mun Stop)","tc":"港鐵屯門站 (輕鐵屯門站)"},
  "K51A-D200": {"en":"SKH St. Simon's Lui Ming Choi Secondary School","tc":"聖公會聖西門呂明才中學"},
  "K51A-D210": {"en":"Prime View Garden","tc":"景峰花園"},
  "K51A-D220": {"en":"LR Fung Tei Stop","tc":"輕鐵鳳地站"},
  "K51A-D230": {"en":"MTR Siu Hong Station (South) (LR Siu Hong Stop)","tc":"港鐵兆康站 (南) (輕鐵兆康站)"},
  "K51A-D240": {"en":"Brilliant Garden","tc":"彩暉花園"},
  "K51A-D250": {"en":"Lingnan University","tc":"嶺南大學"},
  "K51A-D260": {"en":"South Hillcrest","tc":"倚嶺南庭"},
  "K51A-D270": {"en":"Fu Tai","tc":"富泰"},
  "K51A-U010": {"en":"Fu Tai","tc":"富泰"},
  "K51A-U020": {"en":"Beneville","tc":"聚康山莊"},
  "K51A-U030": {"en":"Lingnan University","tc":"嶺南大學"},
  "K51A-U040": {"en":"Brilliant Garden","tc":"彩暉花園"},
  "K51A-U050": {"en":"MTR Siu Hong Station (South) (LR Siu Hong Stop)","tc":"港鐵兆康站 (南) (輕鐵兆康站)"},
  "K51A-U060": {"en":"Tseng Choi Street","tc":"井財街"},
  "K51A-U070": {"en":"ACME Shopping Arcade","tc":"雅都商場"},
  "K51A-U080": {"en":"Tak Ching Court (MTR Tuen Mun Station)","tc":"德政圍 (港鐵屯門站)"},
  "K51A-U090": {"en":"Tuen Mun Town Centre (LR Town Centre Stop)","tc":"屯門市中心 (輕鐵市中心站)"},
  "K51A-U100": {"en":"Tuen Mun Government Secondary School","tc":"屯門官立中學"},
  "K51A-U110": {"en":"Handsome Court","tc":"恒順園"},
  "K51A-U120": {"en":"Harvest Garden","tc":"恒豐園"},
  "K51A-U130": {"en":"Sam Shing Estate","tc":"三聖邨"},
  "K51A-U140": {"en":"Castle Peak Beach","tc":"青山灣"},
  "K51A-U150": {"en":"Seaview Garden","tc":"海景花園"},
  "K51A-U160": {"en":"Cafeteria Beach","tc":"咖啡灣"},
  "K51A-U170": {"en":"Golden Beach","tc":"黃金泳灘"},
  "K51A-U180": {"en":"Hong Kong Gold Coast","tc":"香港黃金海岸"},
  "K51A-U190": {"en":"Aegean Coast","tc":"愛琴海岸"},
  "K51A-U200": {"en":"So Kwun Wat Sub-station","tc":"掃管笏變電站"},
  "K51A-U210": {"en":"So Kwun Wat Tsuen","tc":"掃管笏村"},
  "K51A-U220": {"en":"So Kwun Wat (Mrs. Cheng Yam On Millennium School)","tc":"掃管笏 (鄭任安夫人千禧小學)"},
  "K51A-U230": {"en":"So Kwun Wat Road","tc":"掃管笏路"},
  "K51A-U240": {"en":"18 Kwun Chui Road","tc":"管翠路18號"},
  "K51A-U250": {"en":"So Kwun Wat Tsuen","tc":"掃管笏村"},
  "K52-D010": {"en":"Lung Kwu Tan","tc":"龍鼓灘"},
  "K52-D020": {"en":"No.127 Sha Po Kong","tc":"沙埔崗127號"},
  "K52-D030": {"en":"No.177 Sha Po Kong","tc":"沙埔崗177號"},
  "K52-D040": {"en":"No.288 Sha Po Kong","tc":"沙埔崗288號"},
  "K52-D050": {"en":"No.351 Sha Po Kong","tc":"沙埔崗351號"},
  "K52-D060": {"en":"CLP (Plant A)","tc":"中電 A廠"},
  "K52-D070": {"en":"Shiu Wing Steel Mill","tc":"紹榮鋼鐵"},
  "K52-D080": {"en":"EcoPark","tc":"環保園"},
  "K52-D090": {"en":"River Trade Terminal","tc":"內河碼頭"},
  "K52-D100": {"en":"Government Depot","tc":"政府車場"},
  "K52-D110": {"en":"Pillar Point","tc":"望后石"},
  "K52-D120": {"en":"Butterfly Beach Park","tc":"蝴蝶灣公園"},
  "K52-D130": {"en":"Tuen Mun Public Riding School","tc":"屯門公眾騎術學校"},
  "K52-D140": {"en":"LR Butterfly Stop","tc":"輕鐵蝴蝶站"},
  "K52-D150": {"en":"Light Rail Depot Stop","tc":"輕鐵車廠站"},
  "K52-D160": {"en":"LR Lung Mun Stop","tc":"輕鐵龍門站"},
  "K52-D170": {"en":"LR Tsing Wun Stop","tc":"輕鐵青雲站"},
  "K52-D180": {"en":"LR Kin On Stop","tc":"輕鐵建安站"},
  "K52-D190": {"en":"Tuen Mun Station","tc":"屯門站"},
  "K52-D200": {"en":"Tuen Mun Town Centre","tc":"屯門市中心"},
  "K52-D210": {"en":"Tuen Mun Government Secondary School","tc":"屯門官立中學"},
  "K52-D220": {"en":"Handsome Court","tc":"恒順園"},
  "K52-D230": {"en":"Harvest Garden","tc":"恒豐園"},
  "K52-D240": {"en":"LR Sam Shing Stop","tc":"輕鐵三聖站"},
  "K52-D250": {"en":"Tuen Mun Central Square","tc":"屯門中央廣場"},
  "K52-D260": {"en":"Wu Tsui House, Wu King Estate","tc":"湖景邨湖翠樓"},
  "K52-D270": {"en":"Siu Hei Court","tc":"兆禧苑"},
  "K52-D280": {"en":"Pierhead Garden","tc":"海翠花園"},
  "K52-D290": {"en":"Miami Beach Towers","tc":"邁亞美海灣"},
  "K52-D300": {"en":"Yuet Wu Villa","tc":"悅湖山莊"},
  "K52-U010": {"en":"Yuet Wu Villa","tc":"悅湖山莊"},
  "K52-U020": {"en":"Miami Beach Towers","tc":"邁亞美海灣"},
  "K52-U030": {"en":"Tuen Mun Ferry Pier","tc":"屯門碼頭"},
  "K52-U040": {"en":"Wu Boon House, Wu King Estate","tc":"湖景邨湖畔樓"},
  "K52-U050": {"en":"Wu Tsui House, Wu King Estate","tc":"湖景邨湖翠樓"},
  "K52-U060": {"en":"Tuen Mun Central Square","tc":"屯門中央廣場"},
  "K52-U070": {"en":"LR Sam Shing Stop","tc":"輕鐵三聖站"},
  "K52-U080": {"en":"Mrs Aw Boon Haw Secondary School","tc":"胡陳金枝中學"},
  "K52-U090": {"en":"Tsing Sin Playground","tc":"青善遊樂場"},
  "K52-U100": {"en":"Chi Lok Fa Yuen","tc":"置樂花園"},
  "K52-U110": {"en":"Tuen Mun Government Secondary School","tc":"屯門官立中學"},
  "K52-U120": {"en":"LR Town Centre Stop","tc":"輕鐵市中心站"},
  "K52-U140": {"en":"LR Tuen Mun Stop","tc":"輕鐵屯門站"},
  "K52-U150": {"en":"LR Kin On Stop","tc":"輕鐵建安站"},
  "K52-U160": {"en":"LR Tsing Wun Stop","tc":"輕鐵青雲站"},
  "K52-U170": {"en":"SKH St. Peter's Church","tc":"聖彼得堂"},
  "K52-U180": {"en":"Glorious Garden","tc":"富健花園"},
  "K52-U190": {"en":"Sun Tuen Mun Centre","tc":"新屯門中心"},
  "K52-U200": {"en":"LR Butterfly Stop","tc":"輕鐵蝴蝶站"},
  "K52-U210": {"en":"Tuen Mun Public Riding School","tc":"屯門公眾騎術學校"},
  "K52-U220": {"en":"Butterfly Beach Park","tc":"蝴蝶灣公園"},
  "K52-U230": {"en":"Pillar Point","tc":"望后石"},
  "K52-U240": {"en":"Government Depot","tc":"政府車場"},
  "K52-U250": {"en":"River Trade Terminal","tc":"內河碼頭"},
  "K52-U260": {"en":"EcoPark","tc":"環保園"},
  "K52-U270": {"en":"Shiu Wing Steel Mill","tc":"紹榮鋼鐵"},
  "K52-U280": {"en":"No.312 Sha Po Kong","tc":"沙埔崗312號"},
  "K52-U290": {"en":"No.177 Sha Po Kong","tc":"沙埔崗177號"},
  "K52-U300": {"en":"No.127 Sha Po Kong","tc":"沙埔崗127號"},
  "K52-U310": {"en":"Lung Kwu Tan","tc":"龍鼓灘"},
  "K52A-D010": {"en":"Tsang Tsui (Tsang Tsui Columbarium)","tc":"曾咀 (曾咀靈灰安置所)"},
  "K52A-D020": {"en":"No.127 Sha Po Kong","tc":"沙埔崗127號"},
  "K52A-D030": {"en":"No.177 Sha Po Kong","tc":"沙埔崗177號"},
  "K52A-D040": {"en":"No.288 Sha Po Kong","tc":"沙埔崗288號"},
  "K52A-D050": {"en":"No.351 Sha Po Kong","tc":"沙埔崗351號"},
  "K52A-D060": {"en":"CLP (Plant A)","tc":"中電 A廠"},
  "K52A-D070": {"en":"Shiu Wing Steel Mill","tc":"紹榮鋼鐵"},
  "K52A-D080": {"en":"EcoPark","tc":"環保園"},
  "K52A-D090": {"en":"River Trade Terminal","tc":"內河碼頭"},
  "K52A-D100": {"en":"Government Depot","tc":"政府車場"},
  "K52A-D110": {"en":"Pillar Point","tc":"望后石"},
  "K52A-D120": {"en":"Butterfly Beach Park","tc":"蝴蝶灣公園"},
  "K52A-D130": {"en":"Tuen Mun Public Riding School","tc":"屯門公眾騎術學校"},
  "K52A-D140": {"en":"LR Butterfly Stop","tc":"輕鐵蝴蝶站"},
  "K52A-D150": {"en":"Light Rail Depot Stop","tc":"輕鐵車廠站"},
  "K52A-D160": {"en":"LR Lung Mun Stop","tc":"輕鐵龍門站"},
  "K52A-D170": {"en":"LR Tsing Wun Stop","tc":"輕鐵青雲站"},
  "K52A-D180": {"en":"LR Kin On Stop","tc":"輕鐵建安站"},
  "K52A-D190": {"en":"Tuen Mun Station (LR Tuen Mun Stop)","tc":"屯門站 (輕鐵屯門站)"},
  "K52A-U010": {"en":"Tuen Mun Station (LR Tuen Mun Stop)","tc":"屯門站 (輕鐵屯門站)"},
  "K52A-U015": {"en":"LR Tuen Mun Stop (Please refer to Service Time)*","tc":"輕鐵屯門站 (請留意服務時間)*"},
  "K52A-U020": {"en":"LR Kin On Stop","tc":"輕鐵建安站"},
  "K52A-U030": {"en":"LR Tsing Wun Stop","tc":"輕鐵青雲站"},
  "K52A-U040": {"en":"SKH St. Peter's Church","tc":"聖彼得堂"},
  "K52A-U050": {"en":"Glorious Garden","tc":"富健花園"},
  "K52A-U060": {"en":"Sun Tuen Mun Centre","tc":"新屯門中心"},
  "K52A-U070": {"en":"LR Butterfly Stop","tc":"輕鐵蝴蝶站"},
  "K52A-U080": {"en":"Tuen Mun Public Riding School","tc":"屯門公眾騎術學校"},
  "K52A-U090": {"en":"Butterfly Beach Park","tc":"蝴蝶灣公園"},
  "K52A-U100": {"en":"Pillar Point","tc":"望后石"},
  "K52A-U110": {"en":"Government Depot","tc":"政府車場"},
  "K52A-U120": {"en":"River Trade Terminal","tc":"內河碼頭"},
  "K52A-U130": {"en":"EcoPark","tc":"環保園"},
  "K52A-U140": {"en":"Shiu Wing Steel Mill","tc":"紹榮鋼鐵"},
  "K52A-U150": {"en":"No.312 Sha Po Kong","tc":"沙埔崗312號"},
  "K52A-U160": {"en":"No.177 Sha Po Kong","tc":"沙埔崗177號"},
  "K52A-U170": {"en":"No.127 Sha Po Kong","tc":"沙埔崗127號"},
  "K52A-U180": {"en":"Tsang Tsui (Tsang Tsui Columbarium)","tc":"曾咀 (曾咀靈灰安置所)"},
  "K52P-D010": {"en":"Lung Kwu Tan","tc":"龍鼓灘"},
  "K52P-D020": {"en":"No.127 Sha Po Kong","tc":"沙埔崗127號"},
  "K52P-D030": {"en":"No.177 Sha Po Kong","tc":"沙埔崗177號"},
  "K52P-D040": {"en":"No.288 Sha Po Kong","tc":"沙埔崗288號"},
  "K52P-D050": {"en":"No.351 Sha Po Kong","tc":"沙埔崗351號"},
  "K52P-D060": {"en":"CLP (Plant A)","tc":"中電 A廠"},
  "K52P-D070": {"en":"Shiu Wing Steel Mill","tc":"紹榮鋼鐵"},
  "K52P-D080": {"en":"EcoPark","tc":"環保園"},
  "K52P-D090": {"en":"River Trade Terminal","tc":"內河碼頭"},
  "K52P-D100": {"en":"Government Depot","tc":"政府車場"},
  "K52P-D110": {"en":"Pillar Point","tc":"望后石"},
  "K52P-D120": {"en":"Butterfly Beach Park","tc":"蝴蝶灣公園"},
  "K52P-D130": {"en":"Tuen Mun Public Riding School","tc":"屯門公眾騎術學校"},
  "K52P-D140": {"en":"LR Butterfly Stop","tc":"輕鐵蝴蝶站"},
  "K52P-D150": {"en":"Yuet Wu Villa","tc":"悅湖山莊"},
  "K52P-D160": {"en":"Miami Beach Towers","tc":"邁亞美海灣"},
  "K52P-D170": {"en":"Tuen Mun Ferry Pier","tc":"屯門碼頭"},
  "K52P-D180": {"en":"Wu Boon House, Wu King Estate","tc":"湖景邨湖畔樓"},
  "K52P-D190": {"en":"Wu Tsui House, Wu King Estate","tc":"湖景邨湖翠樓"},
  "K52P-D200": {"en":"Siu Shan Court","tc":"兆山苑"},
  "K52P-D210": {"en":"Light Rail Depot Stop","tc":"輕鐵車廠站"},
  "K52P-D220": {"en":"LR Lung Mun Stop","tc":"輕鐵龍門站"},
  "K52P-D230": {"en":"LR Tsing Wun Stop","tc":"輕鐵青雲站"},
  "K52P-D240": {"en":"LR Kin On Stop","tc":"輕鐵建安站"},
  "K52P-D250": {"en":"Tuen Mun Station","tc":"屯門站"},
  "K53-D010": {"en":"So Kwun Wat (Mrs. Cheng Yam On Millennium School)","tc":"掃管笏 (鄭任安夫人千禧小學)"},
  "K53-D015": {"en":"So Kwun Wat Road","tc":"掃管笏路"},
  "K53-D020": {"en":"18 Kwun Chui Road","tc":"管翠路18號"},
  "K53-D030": {"en":"Kwun Chui Road","tc":"管翠路"},
  "K53-D040": {"en":"Aegean Coast","tc":"愛琴海岸"},
  "K53-D050": {"en":"Hong Kong Gold Coast","tc":"香港黃金海岸"},
  "K53-D060": {"en":"Golden Beach","tc":"黃金泳灘"},
  "K53-D070": {"en":"Cafeteria Beach","tc":"咖啡灣"},
  "K53-D080": {"en":"Bayview Terrace","tc":"碧翠花園"},
  "K53-D090": {"en":"Castle Peak Bay Pier","tc":"青山灣碼頭"},
  "K53-D100": {"en":"Sam Shing Estate","tc":"三聖邨"},
  "K53-D110": {"en":"Hanford Garden (LR Sam Shing Stop)","tc":"恆福花園 (輕鐵三聖站)"},
  "K53-D120": {"en":"Mrs Aw Boon Haw Secondary School","tc":"胡陳金枝中學"},
  "K53-D130": {"en":"Tsing Sin Playground","tc":"青善遊樂場"},
  "K53-D140": {"en":"Chi Lok Fa Yuen","tc":"置樂花園"},
  "K53-D150": {"en":"Tuen Mun Government Secondary School","tc":"屯門官立中學"},
  "K53-D160": {"en":"LR Town Centre Stop","tc":"輕鐵市中心站"},
  "K53-U010": {"en":"Tuen Mun Station (LR Tuen Mun Stop)","tc":"屯門站 (輕鐵屯門站)"},
  "K53-U011": {"en":"Tuen Mun Station (LR Tuen Mun Stop)","tc":"屯門站 (輕鐵屯門站)"},
  "K53-U020": {"en":"Tuen Mun Town Centre","tc":"屯門市中心"},
  "K53-U030": {"en":"Tuen Mun Government Secondary School","tc":"屯門官立中學"},
  "K53-U040": {"en":"Handsome Court","tc":"恒順園"},
  "K53-U050": {"en":"Harvest Garden","tc":"恒豐園"},
  "K53-U060": {"en":"Sam Shing Estate","tc":"三聖邨"},
  "K53-U070": {"en":"Castle Peak Beach","tc":"青山灣"},
  "K53-U080": {"en":"Seaview Garden","tc":"海景花園"},
  "K53-U090": {"en":"Cafeteria Beach","tc":"咖啡灣"},
  "K53-U100": {"en":"Golden Beach","tc":"黃金泳灘"},
  "K53-U110": {"en":"Hong Kong Gold Coast","tc":"香港黃金海岸"},
  "K53-U120": {"en":"Aegean Coast","tc":"愛琴海岸"},
  "K53-U130": {"en":"So Kwun Wat Sub-station","tc":"掃管笏變電站"},
  "K53-U140": {"en":"So Kwun Wat Tsuen","tc":"掃管笏村"},
  "K53S-U010": {"en":"Tuen Mun Station","tc":"屯門站"},
  "K53S-U020": {"en":"Tin Hau Road","tc":"天后路"},
  "K53S-U030": {"en":"Yip Wong Estate","tc":"業旺邨"},
  "K53S-U040": {"en":"Tuen Mun Station","tc":"屯門站"},
  "K54-D010": {"en":"Tuen Mun Town Plaza","tc":"屯門市廣場"},
  "K54-D020": {"en":"San Hui Market","tc":"新墟街市"},
  "K54-D030": {"en":"MTR Siu Hong Station (North) (LR Siu Hong Stop)","tc":"港鐵兆康站 (北) (輕鐵兆康站)"},
  "K54-D040": {"en":"Siu Hong Court","tc":"兆康苑"},
  "K54-D050": {"en":"Yan Po Road Public Transport Interchange","tc":"欣寶路公共運輸交匯處"},
  "K54-D060": {"en":"Ching Tin Estate","tc":"菁田邨"},
  "K54-D070": {"en":"Wo Tin Estate","tc":"和田邨"},
  "K54-U010": {"en":"Wo Tin Estate","tc":"和田邨"},
  "K54-U020": {"en":"Ching Tin Estate","tc":"菁田邨"},
  "K54-U030": {"en":"Tsz Tin Tsuen","tc":"紫田村"},
  "K54-U040": {"en":"Yan Tin Estate","tc":"欣田邨"},
  "K54-U050": {"en":"MTR Siu Hong Station (North) (LR Siu Hong Stop)","tc":"港鐵兆康站 (北) (輕鐵兆康站)"},
  "K54-U060": {"en":"Hung Kiu","tc":"紅橋"},
  "K54-U070": {"en":"Tuen Mun Town Centre","tc":"屯門市中心"},
  "K54A-D010": {"en":"MTR Siu Hong Station (North) (LR Siu Hong Stop)","tc":"港鐵兆康站 (北) (輕鐵兆康站)"},
  "K54A-D020": {"en":"Siu Hong Court","tc":"兆康苑"},
  "K54A-D030": {"en":"Yan Po Road Public Transport Interchange","tc":"欣寶路公共運輸交匯處"},
  "K54A-D040": {"en":"Ching Tin Estate","tc":"菁田邨"},
  "K54A-D050": {"en":"Wo Tin Estate","tc":"和田邨"},
  "K54A-U010": {"en":"Wo Tin Estate","tc":"和田邨"},
  "K54A-U020": {"en":"Ching Tin Estate","tc":"菁田邨"},
  "K54A-U030": {"en":"Tsz Tin Tsuen","tc":"紫田村"},
  "K54A-U040": {"en":"Yan Tin Estate","tc":"欣田邨"},
  "K54A-U050": {"en":"MTR Siu Hong Station (North) (LR Siu Hong Stop)","tc":"港鐵兆康站 (北) (輕鐵兆康站)"},
  "K58-D001": {"en":"So Kwun Wat Tsuen","tc":"掃管笏村"},
  "K58-D002": {"en":"So Kwun Wat (Mrs. Cheng Yam On Millennium School)","tc":"掃管笏  (鄭任安夫人千禧小學)"},
  "K58-D003": {"en":"So Kwun Wat Road","tc":"掃管笏路"},
  "K58-D004": {"en":"18 Kwun Chui Road","tc":"管翠路18號"},
  "K58-D005": {"en":"Kwun Chui Road","tc":"管翠路"},
  "K58-D006": {"en":"Aegean Coast","tc":"愛琴海岸"},
  "K58-D007": {"en":"Hong Kong Gold Coast","tc":"香港黃金海岸"},
  "K58-D008": {"en":"Golden Beach","tc":"黃金泳灘"},
  "K58-D009": {"en":"Cafeteria Beach","tc":"咖啡灣"},
  "K58-D011": {"en":"Bayview Terrace","tc":"碧翠花園"},
  "K58-D012": {"en":"Castle Peak Bay Pier","tc":"青山灣碼頭"},
  "K58-D020": {"en":"Sam Shing Estate","tc":"三聖邨"},
  "K58-D030": {"en":"Mrs Aw Boon Haw Secondary School","tc":"胡陳金枝中學"},
  "K58-D040": {"en":"Tsing Sin Playground","tc":"青善遊樂場"},
  "K58-D050": {"en":"Chi Lok Fa Yuen","tc":"置樂花園"},
  "K58-D060": {"en":"Tuen Mun Government Secondary School","tc":"屯門官立中學"},
  "K58-D070": {"en":"LR Town Centre Stop","tc":"輕鐵市中心站"},
  "K58-D080": {"en":"LR Tuen Mun Stop (MTR Tuen Mun Station)","tc":"輕鐵屯門站 (港鐵屯門站)"},
  "K58-D090": {"en":"LR Kin On Stop","tc":"輕鐵建安站"},
  "K58-D100": {"en":"LR Ming Kum Stop","tc":"輕鐵鳴琴站"},
  "K58-D110": {"en":"LR Shek Pai Stop","tc":"輕鐵石排站"},
  "K58-D120": {"en":"LR San Wai Stop","tc":"輕鐵新圍站"},
  "K58-D130": {"en":"LR Tin King Stop","tc":"輕鐵田景站"},
  "K58-D140": {"en":"Tsing Tin Playground","tc":"青田遊樂場"},
  "K58-D150": {"en":"Lok Sang House, Kin Sang Estate","tc":"建生邨樂生樓"},
  "K58-D160": {"en":"Tai Sang House, Kin Sang Estate","tc":"建生邨泰生樓"},
  "K58-D170": {"en":"LR Kei Lun Stop","tc":"輕鐵麒麟站"},
  "K58-D180": {"en":"Yan Tin Estate","tc":"欣田邨"},
  "K58-D190": {"en":"MTR Siu Hong Station (South) (LR Siu Hong Stop)","tc":"港鐵兆康站 (南) (輕鐵兆康站)"},
  "K58-D193": {"en":"Brilliant Garden","tc":"彩暉花園"},
  "K58-D196": {"en":"Lingnan University","tc":"嶺南大學"},
  "K58-D200": {"en":"South Hillcrest","tc":"倚嶺南庭"},
  "K58-D210": {"en":"Fu Tai","tc":"富泰"},
  "K58-U010": {"en":"Fu Tai","tc":"富泰"},
  "K58-U020": {"en":"Beneville","tc":"聚康山莊"},
  "K58-U023": {"en":"Lingnan University","tc":"嶺南大學"},
  "K58-U026": {"en":"Brilliant Garden","tc":"彩暉花園"},
  "K58-U030": {"en":"MTR Siu Hong Station (South) (LR Siu Hong Stop)","tc":"港鐵兆康站 (南) (輕鐵兆康站)"},
  "K58-U040": {"en":"Siu Hong Court","tc":"兆康苑"},
  "K58-U050": {"en":"LR Kei Lun Stop","tc":"輕鐵麒麟站"},
  "K58-U060": {"en":"Tuen Mun Hospital","tc":"屯門醫院"},
  "K58-U070": {"en":"Tsing Chung Koon","tc":"青松觀"},
  "K58-U080": {"en":"PLK Vicwood K.T. Chong No.2 Primary School","tc":"保良局莊啟程第二小學"},
  "K58-U090": {"en":"Ho Sau Kei Primary School","tc":"何壽基小學"},
  "K58-U100": {"en":"Leung King Estate","tc":"良景邨"},
  "K58-U110": {"en":"LR San Wai Stop","tc":"輕鐵新圍站"},
  "K58-U120": {"en":"LR Shek Pai Stop","tc":"輕鐵石排站"},
  "K58-U130": {"en":"LR Ming Kum Stop","tc":"輕鐵鳴琴站"},
  "K58-U140": {"en":"LR Kin On Stop","tc":"輕鐵建安站"},
  "K58-U150": {"en":"MTR Tuen Mun Station","tc":"港鐵屯門站"},
  "K58-U160": {"en":"Tuen Mun Town Centre","tc":"屯門市中心"},
  "K58-U170": {"en":"Tuen Mun Government Secondary School","tc":"屯門官立中學"},
  "K58-U180": {"en":"Handsome Court","tc":"恒順園"},
  "K58-U190": {"en":"Harvest Garden","tc":"恒豐園"},
  "K58-U200": {"en":"Sam Shing Estate","tc":"三聖邨"},
  "K58-U215": {"en":"Castle Peak Beach","tc":"青山灣"},
  "K58-U220": {"en":"Seaview Garden","tc":"海景花園"},
  "K58-U230": {"en":"Cafeteria Beach","tc":"咖啡灣"},
  "K58-U240": {"en":"Golden Beach","tc":"黃金泳灘"},
  "K58-U250": {"en":"Hong Kong Gold Coast","tc":"香港黃金海岸"},
  "K58-U260": {"en":"Aegean Coast","tc":"愛琴海岸"},
  "K58-U270": {"en":"So Kwun Wat Sub-station","tc":"掃管笏變電站"},
  "K58-U280": {"en":"So Kwun Wat Tsuen","tc":"掃管笏村"},
  "K58-U290": {"en":"So Kwun Wat (Mrs. Cheng Yam On Millennium School)","tc":"掃管笏 (鄭任安夫人千禧小學)"},
  "K58-U300": {"en":"So Kwun Wat Road","tc":"掃管笏路"},
  "K58-U310": {"en":"18 Kwun Chui Road","tc":"管翠路18號"},
  "K58-U320": {"en":"Kwun Chui Road","tc":"管翠路"},
  "K65-D010": {"en":"Lau Fau Shan","tc":"流浮山"},
  "K65-D020": {"en":"San Hing Tsuen","tc":"新慶村"},
  "K65-D030": {"en":"Sha Kong Wai","tc":"沙江圍"},
  "K65-D040": {"en":"Fung Kong Tsuen","tc":"鳳降村"},
  "K65-D050": {"en":"Tung Tau Tsuen","tc":"東頭村"},
  "K65-D060": {"en":"Lo Uk Tsuen","tc":"羅屋村"},
  "K65-D070": {"en":"Shek Kong Wai","tc":"錫降圍"},
  "K65-D080": {"en":"Ha Tsuen","tc":"廈村"},
  "K65-D090": {"en":"Sha Chau Lei Tsuen","tc":"沙洲里村"},
  "K65-D100": {"en":"Tin Shing Court (MTR Tin Shui Wai Station)","tc":"天盛苑 (港鐵天水圍站)"},
  "K65-D110": {"en":"LR Hang Mei Tsuen Stop","tc":"輕鐵坑尾村站"},
  "K65-D120": {"en":"Hang Mei Tsuen","tc":"坑尾村"},
  "K65-D130": {"en":"Ping Hing Lane, Ping Shan","tc":"屏山屏興里"},
  "K65-D140": {"en":"LR Ping Shan Stop","tc":"輕鐵屏山站"},
  "K65-D150": {"en":"LR Shui Pin Wai Stop","tc":"輕鐵水邊圍站"},
  "K65-D160": {"en":"Yuen Long Plaza","tc":"元朗廣場"},
  "K65-D170": {"en":"Yuen Long Landmark","tc":"開心廣場"},
  "K65-D180": {"en":"Kuk Ting Street","tc":"谷亭街"},
  "K65-D190": {"en":"Yuen Long Station (LR Yuen Long Stop, MTR Yuen Long Station)","tc":"元朗站 (輕鐵元朗站, 港鐵元朗站)"},
  "K65-U010": {"en":"Yuen Long Station (LR Yuen Long Stop) (MTR Yuen Long Station)","tc":"元朗站 (輕鐵元朗站) (港鐵元朗站)"},
  "K65-U020": {"en":"Yau San Street","tc":"又新街"},
  "K65-U030": {"en":"Tai Tong Road","tc":"大棠路"},
  "K65-U040": {"en":"Hong Lok Road","tc":"康樂路"},
  "K65-U050": {"en":"Yuen Long Police Station","tc":"元朗警署"},
  "K65-U060": {"en":"LR Shui Pin Wai Stop","tc":"輕鐵水邊圍站"},
  "K65-U070": {"en":"Yuen Long Park","tc":"元朗公園"},
  "K65-U080": {"en":"Long Bin","tc":"朗邊"},
  "K65-U090": {"en":"Ping Hing Lane, Ping Shan","tc":"屏山屏興里"},
  "K65-U100": {"en":"Hang Mei Tsuen","tc":"坑尾村"},
  "K65-U110": {"en":"LR Hang Mei Tsuen Stop","tc":"輕鐵坑尾村站"},
  "K65-U120": {"en":"Tin Shing Court (MTR Tin Shui Wai Station)","tc":"天盛苑 (港鐵天水圍站)"},
  "K65-U130": {"en":"Shek Po Road","tc":"石埗路"},
  "K65-U140": {"en":"Sha Chau Lei Tsuen","tc":"沙洲里村"},
  "K65-U150": {"en":"Ha Tsuen","tc":"廈村"},
  "K65-U160": {"en":"Shek Kong Wai","tc":"錫降圍"},
  "K65-U170": {"en":"Lo Uk Tsuen","tc":"羅屋村"},
  "K65-U180": {"en":"Tung Tau Tsuen (South)","tc":"東頭村 (南)"},
  "K65-U190": {"en":"Tung Tau Tsuen (North)","tc":"東頭村 (北)"},
  "K65-U200": {"en":"Fung Kong Tsuen","tc":"鳳降村"},
  "K65-U210": {"en":"Sha Kong Wai","tc":"沙江圍"},
  "K65-U220": {"en":"San Hing Tsuen","tc":"新慶村"},
  "K65-U230": {"en":"Lau Fau Shan","tc":"流浮山"},
  "K65A-D010": {"en":"Lau Fau Shan","tc":"流浮山"},
  "K65A-D020": {"en":"San Hing Tsuen","tc":"新慶村"},
  "K65A-D030": {"en":"Sha Kong Wai","tc":"沙江圍"},
  "K65A-D040": {"en":"Fung Kong Tsuen","tc":"鳳降村"},
  "K65A-D050": {"en":"Tung Tau Tsuen","tc":"東頭村"},
  "K65A-D060": {"en":"Lo Uk Tsuen","tc":"羅屋村"},
  "K65A-D070": {"en":"Shek Kong Wai","tc":"錫降圍"},
  "K65A-D080": {"en":"Ha Tsuen","tc":"廈村"},
  "K65A-D090": {"en":"Sha Chau Lei Tsuen","tc":"沙洲里村"},
  "K65A-D100": {"en":"Tin Shing Court (MTR Tin Shui Wai Station)","tc":"天盛苑 (港鐵天水圍站)"},
  "K65A-D110": {"en":"Tin Shui Wai Station (LR Tin Shui Wai Stop)","tc":"天水圍站 (輕鐵天水圍站)"},
  "K65A-U010": {"en":"Tin Shui Wai Station (LR Tin Shui Wai Stop)","tc":"天水圍站 (輕鐵天水圍站)"},
  "K65A-U020": {"en":"Tin Shing Court (MTR Tin Shui Wai Station)","tc":"天盛苑 (港鐵天水圍站)"},
  "K65A-U030": {"en":"Shek Po Road","tc":"石埗路"},
  "K65A-U040": {"en":"Sha Chau Lei Tsuen","tc":"沙洲里村"},
  "K65A-U050": {"en":"Ha Tsuen","tc":"廈村"},
  "K65A-U060": {"en":"Shek Kong Wai","tc":"錫降圍"},
  "K65A-U070": {"en":"Lo Uk Tsuen","tc":"羅屋村"},
  "K65A-U080": {"en":"Tung Tau Tsuen (South)","tc":"東頭村 (南)"},
  "K65A-U090": {"en":"Tung Tau Tsuen (North)","tc":"東頭村 (北)"},
  "K65A-U100": {"en":"Fung Kong Tsuen","tc":"鳳降村"},
  "K65A-U110": {"en":"Sha Kong Wai","tc":"沙江圍"},
  "K65A-U120": {"en":"San Hing Tsuen","tc":"新慶村"},
  "K65A-U130": {"en":"Lau Fau Shan","tc":"流浮山"},
  "K66-D010": {"en":"Tai Tong Wong Nai Tun Tsuen","tc":"大棠黃泥墩村"},
  "K66-D020": {"en":"Tai Tong Shan Road","tc":"大棠山路"},
  "K66-D030": {"en":"Tai Tong Roundabout","tc":"大棠迴旋處"},
  "K66-D040": {"en":"Wah Yuen","tc":"華苑"},
  "K66-D050": {"en":"Shui Chiu San Tsuen","tc":"水蕉新村"},
  "K66-D060": {"en":"Nam Hang Pai","tc":"南坑排"},
  "K66-D070": {"en":"Nam Hang Tsuen","tc":"南坑村"},
  "K66-D080": {"en":"Hung Tso Tin Tsuen","tc":"紅棗田村"},
  "K66-D090": {"en":"Po Shing Wai","tc":"普盛圍"},
  "K66-D100": {"en":"Shung Ching School","tc":"崇正公立學校"},
  "K66-D110": {"en":"Law Ka Yuen","tc":"羅家園"},
  "K66-D120": {"en":"Sham Chung Tsuen","tc":"深涌村"},
  "K66-D130": {"en":"Fraser Village","tc":"禮修村"},
  "K66-D140": {"en":"Sereno Verde","tc":"蝶翠峰"},
  "K66-D150": {"en":"Hang Heung Cake Shop","tc":"恆香製餅廠"},
  "K66-D160": {"en":"Manhattan Plaza","tc":"富達廣場"},
  "K66-D170": {"en":"Citi Mall","tc":"千色廣場"},
  "K66-D180": {"en":"On Hong Road","tc":"安康路"},
  "K66-D190": {"en":"Yuen Long Town Hall","tc":"元朗大會堂"},
  "K66-D200": {"en":"Hong Shui House, Shui Pin Wai Estate","tc":"水邊圍邨康水樓"},
  "K66-D210": {"en":"Yuet Ping House, Long Ping Estate","tc":"朗屏邨悅屏樓"},
  "K66-D220": {"en":"Wai Chow School","tc":"惠州學校"},
  "K66-D230": {"en":"Chu Ping House, Long Ping Estate","tc":"朗屏邨珠屏樓"},
  "K66-D240": {"en":"Long Ping","tc":"朗屏"},
  "K66-U010": {"en":"Long Ping","tc":"朗屏"},
  "K66-U020": {"en":"Yeung Uk Tsuen","tc":"楊屋村"},
  "K66-U030": {"en":"Ping Cheong Path (MTR Long Ping Station)","tc":"屏昌徑 (港鐵朗屏站)"},
  "K66-U040": {"en":"Yuen Long Home for the Aged Blind","tc":"元朗盲人安老院"},
  "K66-U050": {"en":"Yuen Long Town Hall (LR Fung Nin Road Stop)","tc":"元朗大會堂 (輕鐵豐年路站)"},
  "K66-U060": {"en":"On Hong Road","tc":"安康路"},
  "K66-U070": {"en":"Yuen Long Commercial Centre","tc":"元朗商業中心"},
  "K66-U080": {"en":"Manhattan Plaza","tc":"富達廣場"},
  "K66-U090": {"en":"Sereno Verde","tc":"蝶翠峰"},
  "K66-U100": {"en":"Fraser Village","tc":"禮修村"},
  "K66-U110": {"en":"Sham Chung Tsuen","tc":"深涌村"},
  "K66-U120": {"en":"Law Ka Yuen","tc":"羅家園"},
  "K66-U130": {"en":"Shung Ching School","tc":"崇正公立學校"},
  "K66-U140": {"en":"Shung Ching Vegetable Market","tc":"崇正菜站"},
  "K66-U150": {"en":"Lo Wai","tc":"老圍"},
  "K66-U160": {"en":"Chun Wah Villas","tc":"振華花園"},
  "K66-U170": {"en":"Nam Hang Pai","tc":"南坑排"},
  "K66-U180": {"en":"Shui Chiu San Tsuen","tc":"水蕉新村"},
  "K66-U190": {"en":"Wah Yuen","tc":"華苑"},
  "K66-U200": {"en":"Tai Tong Roundabout","tc":"大棠迴旋處"},
  "K66-U210": {"en":"Tai Tong Shan Road","tc":"大棠山路"},
  "K66-U220": {"en":"Tai Tong Wong Nai Tun Tsuen","tc":"大棠黃泥墩村"},
  "K68-D010": {"en":"Yuen Long Park","tc":"元朗公園"},
  "K68-D020": {"en":"Park Royale","tc":"御豪山莊"},
  "K68-D030": {"en":"Villa Art Deco","tc":"藝典居"},
  "K68-D040": {"en":"Springdale Villas","tc":"御庭居"},
  "K68-D050": {"en":"Yuen Long Swimming Pool","tc":"元朗游泳池"},
  "K68-D060": {"en":"Yuen Long Town Hall","tc":"元朗大會堂"},
  "K68-D070": {"en":"Yuen Long Plaza","tc":"元朗廣場"},
  "K68-D080": {"en":"Yuen Long On Ning Road","tc":"元朗安寧路"},
  "K68-D090": {"en":"Tai Kiu Tsuen","tc":"大橋村"},
  "K68-D100": {"en":"Wai Chow School","tc":"惠州學校"},
  "K68-D110": {"en":"Chu Ping House, Long Ping Estate","tc":"朗屏邨珠屏樓"},
  "K68-D120": {"en":"Long Ping","tc":"朗屏"},
  "K68-D130": {"en":"Wang Chau Fuk Hing Tsuen","tc":"橫洲福慶村"},
  "K68-D140": {"en":"Yuen Long Textile Co Ltd","tc":"元朗紡織品"},
  "K68-D150": {"en":"DCH Food Processing & Logistics Centre","tc":"大昌行食品加工及物流中心"},
  "K68-D160": {"en":"Yau Sang Galvanizers (Hot-Dip) Co Ltd","tc":"有生鉛水(熱浸鋅)"},
  "K68-D170": {"en":"Eu Yan Sang Centre","tc":"余仁生中心"},
  "K68-D180": {"en":"Yuen Long Sewage Treatment Works","tc":"元朗污水處理廠"},
  "K68-D190": {"en":"Nestle (HK) Ltd","tc":"雀巢"},
  "K68-D200": {"en":"Ushio HK Ltd","tc":"牛尾香港"},
  "K68-U010": {"en":"Yuen Long Industrial Estate","tc":"元朗工業邨"},
  "K68-U011": {"en":"Yuen Long Industrial Estate","tc":"元朗工業邨"},
  "K68-U020": {"en":"Toppan Forms Card Tech Ltd","tc":"凸版資訊卡"},
  "K68-U030": {"en":"Nestle (HK) Ltd","tc":"雀巢"},
  "K68-U040": {"en":"Yuen Long Sewage Treatment Works","tc":"元朗污水處理廠"},
  "K68-U050": {"en":"Wai Yuen Tong Medicine Building","tc":"位元堂藥業大廈"},
  "K68-U060": {"en":"TDK Manufacturing (HK) Co Ltd","tc":"東電化電子零件"},
  "K68-U070": {"en":"Toppan Printing Co (HK) Ltd","tc":"凸版印刷"},
  "K68-U080": {"en":"Telford International Industries Ltd","tc":"匯泉國際實業"},
  "K68-U090": {"en":"Wang Chau Fuk Hing Tsuen","tc":"橫洲福慶村"},
  "K68-U100": {"en":"Long Ping","tc":"朗屏"},
  "K68-U110": {"en":"Yeung Uk Tsuen","tc":"楊屋村"},
  "K68-U120": {"en":"Ping Cheong Path (MTR Long Ping Station)","tc":"屏昌徑 (港鐵朗屏站)"},
  "K68-U130": {"en":"Yuen Long Home for the Aged Blind","tc":"元朗盲人安老院"},
  "K68-U140": {"en":"Lut Sau Hall (LR Fung Nin Road Stop)","tc":"聿修堂 (輕鐵豐年路站)"},
  "K68-U150": {"en":"Yuen Long Theatre","tc":"元朗劇院"},
  "K68-U160": {"en":"Silver Field Garden","tc":"銀田花園"},
  "K68-U170": {"en":"South Yuen Long Government Primary School","tc":"南元朗官立小學"},
  "K73-D010": {"en":"Yuen Long West (LR Fung Nin Road Stop)","tc":"元朗西 (輕鐵豐年路站)"},
  "K73-D020": {"en":"Yuen Long On Ning Road","tc":"元朗安寧路"},
  "K73-D030": {"en":"Tai Kiu Tsuen (MTR Long Ping Station)","tc":"大橋村 (港鐵朗屏站)"},
  "K73-D040": {"en":"Wai Chow School","tc":"惠州學校"},
  "K73-D050": {"en":"Chu Ping House, Long Ping Estate","tc":"朗屏邨珠屏樓"},
  "K73-D070": {"en":"Long Ping (Bus Terminus)","tc":"朗屏 (巴士總站)"},
  "K73-D080": {"en":"Fung Chi Tsuen","tc":"鳳池村"},
  "K73-D090": {"en":"LR Tin Tsz Stop","tc":"輕鐵天慈站"},
  "K73-D100": {"en":"Tin Shui Wai Swimming Pool","tc":"天水圍游泳池"},
  "K73-D110": {"en":"Kenswood Court, Tin Lung Road","tc":"天龍路景湖居"},
  "K73-D120": {"en":"Lynwood Court, Tin Kwai Road","tc":"天葵路麗湖居"},
  "K73-D130": {"en":"Ching Wan House, Tin Ching Estate","tc":"天晴邨晴雲樓"},
  "K73-D140": {"en":"Nang Fu House, Tin Fu Court","tc":"天富苑能富閣"},
  "K73-D150": {"en":"Tin Chak Estate","tc":"天澤邨"},
  "K73-D160": {"en":"Tin Heng","tc":"天恆"},
  "K73-U010": {"en":"Tin Heng","tc":"天恆"},
  "K73-U020": {"en":"Yat Tam House, Tin Yat Estate","tc":"天逸邨逸潭樓"},
  "K73-U025": {"en":"Tin Yan","tc":"天恩"},
  "K73-U030": {"en":"Yat Yeung House, Tin Yat Estate","tc":"天逸邨逸洋樓"},
  "K73-U040": {"en":"Ching Pik House, Tin Ching Estate","tc":"天晴邨晴碧樓"},
  "K73-U045": {"en":"Tin Yuet Estate","tc":"天悅邨"},
  "K73-U050": {"en":"HKFYG Lee Shau Kee College","tc":"香港青年協會李兆基書院"},
  "K73-U060": {"en":"Maywood Court, Tin Kwai Road","tc":"天葵路美湖居"},
  "K73-U070": {"en":"Kenswood Court, Tin Shing Road","tc":"天城路景湖居"},
  "K73-U080": {"en":"Tin Tsz Estate","tc":"天慈邨"},
  "K73-U090": {"en":"Fung Chi Tsuen","tc":"鳳池村"},
  "K73-U100": {"en":"Long Ping","tc":"朗屏"},
  "K73-U110": {"en":"Yuen Long Home for the Aged Blind","tc":"元朗盲人安老院"},
  "K73-U120": {"en":"Yuen Long West","tc":"元朗西"},
  "K74-D010": {"en":"Tung Shing Lei","tc":"東成里"},
  "K74-D020": {"en":"TWGHs C.Y.Ma Memorial College (near Long Shin Estate)","tc":"東華三院馬振玉中學(近朗善邨)"},
  "K74-D030": {"en":"Tai Kiu Tsuen (MTR Long Ping Station)","tc":"大橋村 (港鐵朗屏站)"},
  "K74-D040": {"en":"Wai Chow School","tc":"惠州學校"},
  "K74-D050": {"en":"Chu Ping House, Long Ping Estate","tc":"朗屏邨珠屏樓"},
  "K74-D060": {"en":"Long Ping (Bus Terminus)","tc":"朗屏 (巴士總站)"},
  "K74-D070": {"en":"Fung Chi Tsuen","tc":"鳳池村"},
  "K74-D080": {"en":"LR Tin Tsz Stop","tc":"輕鐵天慈站"},
  "K74-D090": {"en":"Tin Shui Wai Park","tc":"天水圍公園"},
  "K74-D100": {"en":"Tin Wah Estate","tc":"天華邨"},
  "K74-D110": {"en":"Tin Yuet Estate","tc":"天悅邨"},
  "K74-U001": {"en":"Tin Shui Wai Town Centre","tc":"天水圍市中心"},
  "K74-U002": {"en":"Tin Shui Wai Town Centre","tc":"天水圍市中心"},
  "K74-U004": {"en":"Chung Ki House Tin Chung Court","tc":"天頌苑頌棋閣"},
  "K74-U007": {"en":"Tin Chung Court","tc":"天頌苑"},
  "K74-U010": {"en":"Tin Shui","tc":"天瑞"},
  "K74-U011": {"en":"Tin Shui","tc":"天瑞"},
  "K74-U020": {"en":"Tin Shui Wai Park","tc":"天水圍公園"},
  "K74-U030": {"en":"Tin Tsz Estate","tc":"天慈邨"},
  "K74-U040": {"en":"Fung Chi Tsuen","tc":"鳳池村"},
  "K74-U050": {"en":"Long Ping (Bus Terminus)","tc":"朗屏 (巴士總站)"},
  "K74-U060": {"en":"Yuen Long Home for the Aged Blind","tc":"元朗盲人安老院"},
  "K74-U070": {"en":"Yuen Long Plaza (LR Fung Nin Road Stop)","tc":"元朗廣場 (輕鐵豐年路站)"},
  "K74-U080": {"en":"Yuen Long Landmark","tc":"開心廣場"},
  "K74-U090": {"en":"MTR Yuen Long Station (Long Yat Road) (MTR Yuen Long Station)","tc":"港鐵元朗站(朗日路)  (港鐵元朗站)"},
  "K74-U100": {"en":"Pok Oi Hospital","tc":"博愛醫院"},
  "K75A-D010": {"en":"LR Hung Shui Kiu Stop","tc":"輕鐵洪水橋站"},
  "K75A-D020": {"en":"Rural Committee","tc":"鄉事委員會"},
  "K75A-D030": {"en":"Tin Sam","tc":"田心"},
  "K75A-D040": {"en":"San Lee Uk Tsuen","tc":"新李屋村"},
  "K75A-D050": {"en":"San Sang Tsuen","tc":"新生村"},
  "K75A-D060": {"en":"Lee Uk Tsuen","tc":"李屋村"},
  "K75A-D070": {"en":"San Uk Tsuen","tc":"新屋村"},
  "K75A-D080": {"en":"Ha Tsuen Shi","tc":"廈村市"},
  "K75A-D090": {"en":"Ha Tsuen","tc":"廈村"},
  "K75A-D100": {"en":"Sha Chau Lei Tsuen","tc":"沙洲里村"},
  "K75A-D110": {"en":"Tin Shing Court (MTR Tin Shui Wai Station)","tc":"天盛苑 (港鐵天水圍站)"},
  "K75A-U010": {"en":"Tin Shui Wai Station (LR Tin Shui Wai Stop)","tc":"天水圍站 (輕鐵天水圍站)"},
  "K75A-U011": {"en":"Tin Shui Wai Station (LR Tin Shui Wai Stop)","tc":"天水圍站 (輕鐵天水圍站)"},
  "K75A-U020": {"en":"Tin Shing Court (MTR Tin Shui Wai Station)","tc":"天盛苑 (港鐵天水圍站)"},
  "K75A-U030": {"en":"Shek Po Tsuen","tc":"石埗村"},
  "K75P-D010": {"en":"LR Hung Shui Kiu Stop","tc":"輕鐵洪水橋站"},
  "K75P-D020": {"en":"Hung Shui Kiu Bus Depot","tc":"洪水橋巴士廠"},
  "K75P-D030": {"en":"Hung Fuk Estate","tc":"洪福邨"},
  "K75P-D040": {"en":"Shek Po Tsuen","tc":"石埗村"},
  "K75P-D050": {"en":"Tin Shing Court","tc":"天盛苑"},
  "K75P-D060": {"en":"Tin Shui Wai Police Station","tc":"天水圍警署"},
  "K75P-D070": {"en":"Sherwood Court","tc":"賞湖居"},
  "K75P-D080": {"en":"Tin Shui Wai Park","tc":"天水圍公園"},
  "K75P-U010": {"en":"Tin Shui","tc":"天瑞"},
  "K75P-U011": {"en":"Tin Shui","tc":"天瑞"},
  "K75P-U020": {"en":"Tin Shui Wai Park","tc":"天水圍公園"},
  "K75P-U030": {"en":"Yiu Shing House, Tin Yiu Estate","tc":"天耀邨耀盛樓"},
  "K75P-U040": {"en":"LR Tin Yiu Stop","tc":"輕鐵天耀站"},
  "K75P-U050": {"en":"Tin Shing Court (MTR Tin Shui Wai Station)","tc":"天盛苑 (港鐵天水圍站)"},
  "K75P-U060": {"en":"Shek Po Road","tc":"石埗路"},
  "K75P-U070": {"en":"Sha Chau Lei Tsuen","tc":"沙洲里村"},
  "K75P-U080": {"en":"Ha Tsuen Shi","tc":"廈村市"},
  "K75P-U090": {"en":"San Uk Tsuen","tc":"新屋村"},
  "K75P-U100": {"en":"Lee Uk Tsuen","tc":"李屋村"},
  "K75P-U110": {"en":"San Sang Tsuen","tc":"新生村"},
  "K75P-U120": {"en":"San Lee Uk Tsuen","tc":"新李屋村"},
  "K75P-U130": {"en":"Tin Sam","tc":"田心"},
  "K75P-U140": {"en":"Rural Committee","tc":"鄉事委員會"},
  "K75S-D010": {"en":"Hung Fuk Estate","tc":"洪福邨"},
  "K75S-D020": {"en":"Shek Po Tsuen","tc":"石埗村"},
  "K75S-D030": {"en":"Tin Shing Court","tc":"天盛苑"},
  "K75S-U010": {"en":"Tin Shui Wai Station","tc":"天水圍站"},
  "K75S-U011": {"en":"Tin Shui Wai Station","tc":"天水圍站"},
  "K75S-U020": {"en":"Tin Shing Court","tc":"天盛苑"},
  "K75S-U030": {"en":"Shek Po Tsuen","tc":"石埗村"},
  "K75S-U040": {"en":"Hung Shui Kiu Bus Depot","tc":"洪水橋巴士廠"},
  "K76-D010": {"en":"Tin Shui Wai Station (MTR Tin Shui Wai Station)","tc":"天水圍站 (港鐵天水圍站)"},
  "K76-D020": {"en":"Tin Yan Estate","tc":"天恩邨"},
  "K76-D030": {"en":"Tin Chak Estate","tc":"天澤邨"},
  "K76-D040": {"en":"Tin Heng","tc":"天恆"},
  "K76-U010": {"en":"Tin Heng","tc":"天恆"},
  "K76-U020": {"en":"Yat Tam House, Tin Yat Estate","tc":"天逸邨逸潭樓"},
  "K76-U030": {"en":"Yan Fu House, Tin Fu Court","tc":"天富苑欣富閣"},
  "K76-U040": {"en":"Tin Shing Court (MTR Tin Shui Wai Station)","tc":"天盛苑 (港鐵天水圍站)"},
  "K76-U050": {"en":"Tin Shui Wai Station (MTR Tin Shui Wai Station)","tc":"天水圍站 (港鐵天水圍站)"},
  "K76S-D010": {"en":"Tin Shui Wai Station","tc":"天水圍站"},
  "K76S-D020": {"en":"Tin Yan Estate","tc":"天恩邨"},
  "K76S-D030": {"en":"Tin Chak Estate","tc":"天澤邨"},
  "K76S-D040": {"en":"LR Wetland Park Stop","tc":"輕鐵濕地公園站"},
  "K76S-D050": {"en":"Wetland Park Road (near Tin Kwai Road)","tc":"濕地公園路(近天葵路)"},
  "K76S-U010": {"en":"Wetland Park Road (near Tin Kwai Road)","tc":"濕地公園路(近天葵路)"},
  "K76S-U015": {"en":"LR Wetland Park Stop","tc":"輕鐵濕地公園站"},
  "K76S-U020": {"en":"Yat Tam House, Tin Yat Estate","tc":"天逸邨逸潭樓"},
  "K76S-U030": {"en":"Yan Fu House, Tin Fu Court","tc":"天富苑欣富閣"},
  "K76S-U040": {"en":"Tin Shing Court","tc":"天盛苑"}
};
